# Example configuration file for Luminary

# LLM provider configuration
llm:
  provider: mock  # mock, openrouter
  model: anthropic/claude-3.5-sonnet
  temperature: 0.7
  max_tokens: 2000
  top_p: 0.9

# Comment validator configuration
validator:
  enabled: false  # Set to true to enable validation
  provider: null  # null = use same as llm provider
  model: null  # null = use same as llm model
  threshold: 0.7  # Minimum score threshold (0.0-1.0)

# Files to ignore
ignore:
  patterns:
    - "*.lock"
    - "*.min.js"
    - "*.min.css"
    - "*.map"
    - "node_modules/**"
    - ".git/**"
  binary_files: true

# Limits
limits:
  max_files: null  # null = no limit
  max_lines: null
  max_context_tokens: null

# Comment settings
comments:
  mode: both  # inline, summary, both
  severity_levels: true
  markdown: true

# Retry configuration
retry:
  max_attempts: 3
  backoff_multiplier: 2
  initial_delay: 1  # seconds
